load("@aspect_bazel_lib//lib:jq.bzl", "jq")
load(":fixture.bzl", "release_archive")

package(default_visibility = ["//e2e:__subpackages__"])

exports_files([
    "attestations",
    "empty-prefix",
    "missing-module-name",
    "multi-module",
    "no-github-id",
    "no-prefix",
    "tarball",
    "tarball-xz",
    "unversioned",
    "versioned",
    "zero-versioned",
    "zip",
])

release_archive(
    name = "attestations_1.0.0",
    out = "attestations-v1.0.0.tar.gz",
    extension = "tar.gz",
    fixture = "attestations",
    prefix = "attestations-1.0.0",
)

# attestation artifacts to go along with the above release archive
jq(
    name = "source_attestation",
    srcs = [],
    out = "source.json.intoto.jsonl",
    filter = "{}",
)

jq(
    name = "module_attestation",
    srcs = [],
    out = "MODULE.bazel.intoto.jsonl",
    filter = "{}",
)

jq(
    name = "archive_attestation",
    srcs = [],
    out = "attestations-v1.0.0.tar.gz.intoto.jsonl",
    filter = "{}",
)

release_archive(
    name = "empty-prefix_1.0.0",
    out = "empty-prefix-v1.0.0.tar.gz",
    extension = "tar.gz",
    fixture = "empty-prefix",
    prefix = "",
)

release_archive(
    name = "missing-module-name_1.0.0",
    out = "missing-module-name-1.0.0.tar.gz",
    extension = "tar.gz",
    fixture = "missing-module-name",
    prefix = "missing-module-name-1.0.0",
)

release_archive(
    name = "multi-module_1.0.0",
    out = "multi-module-v1.0.0.tar.gz",
    extension = "tar.gz",
    fixture = "multi-module",
    prefix = "multi-module-1.0.0",
)

release_archive(
    name = "no-prefix_1.0.0",
    out = "no-prefix-v1.0.0.tar.gz",
    extension = "tar.gz",
    fixture = "no-prefix",
    prefix = "",
)

release_archive(
    name = "tarball_1.0.0",
    out = "tarball-v1.0.0.tar.gz",
    extension = "tar.gz",
    fixture = "tarball",
    prefix = "tarball-1.0.0",
)

release_archive(
    name = "tarball-xz_1.0.0",
    out = "tarball-xz-v1.0.0.tar.xz",
    extension = "tar.xz",
    fixture = "tarball-xz",
    prefix = "tarball-xz-1.0.0",
)

release_archive(
    name = "unversioned_1.0.0",
    out = "unversioned-v1.0.0.tar.gz",
    extension = "tar.gz",
    fixture = "unversioned",
    prefix = "unversioned-1.0.0",
)

release_archive(
    name = "versioned_1.0.0",
    out = "versioned-v1.0.0.tar.gz",
    extension = "tar.gz",
    fixture = "versioned",
    prefix = "versioned-1.0.0",
)

release_archive(
    name = "zero-versioned_1.0.0",
    out = "zero-versioned-v1.0.0.tar.gz",
    extension = "tar.gz",
    fixture = "zero-versioned",
    prefix = "zero-versioned-1.0.0",
)

release_archive(
    name = "zip_1.0.0",
    out = "zip-v1.0.0.zip",
    extension = "zip",
    fixture = "zip",
    prefix = "zip-1.0.0",
)
